export {
  AvatarCall,
  useAvatarCall,
  type AvatarCallEndReason,
  type AvatarCallHandle,
  type AvatarCallProps,
  type AvatarCallStatus,
} from "./avatar-call";
export { RealtimeAvatarProvider, useRealtimeAvatarClient, useRealtimeAvatarContext } from "./provider";
export {
  AudioTrack,
  ConnectionState,
  ConnectionStateToast,
  DEFAULT_AVATAR_PLAYOUT_DELAY_SECONDS,
  DisconnectReason,
  LiveKitRoom,
  RealtimeAvatarLiveKitRoom,
  Room,
  RoomAudioRenderer,
  RoomEvent,
  StartAudio,
  Track,
  TrackToggle,
  VideoTrack,
  capacityErrorFromBusy,
  capacityStateFromGrant,
  useAvatarPlayoutDelay,
  useChat,
  useConnectionState,
  useLiveKitAvatarGrant,
  useCallTranscript,
  useReleaseMicLeaseOnTrackEnded,
  useLocalParticipant,
  useRoomContext,
  useStartAudio,
  useTrackToggle,
  useTranscriptions,
  useVoiceAssistant,
  splitCallTranscript,
  type CallTranscript,
  type CallTranscriptSegment,
  type LiveKitAvatarGrantState,
  type LiveKitAvatarGrantStatus,
  type LiveKitCapacityState,
  type LiveKitConnectionStatus,
  type RealtimeAvatarLiveKitRoomProps,
  type RemoteAudioTrack,
  type RemoteTrack,
  type RemoteVideoTrack,
  type SendTextOptions,
  type UseLiveKitAvatarGrantInput,
} from "./livekit";
export {
  AvatarVideoSurface,
  createLivePlaybackKeeper,
  isLiveTrackProducing,
  resolveSurfaceLayers,
  type AvatarVideoFit,
  type AvatarVideoSurfaceProps,
  type LivePlaybackKeeper,
  type PlayableVideoElement,
  type SurfaceLayers,
} from "./avatar-video-surface";
export {
  DEFAULT_IDLE_SECONDS,
  DEFAULT_IDLE_WARN_LEAD_SECONDS,
  DEFAULT_TURN_TIMEOUT_SECONDS,
  MAX_RECONNECT_ATTEMPTS,
  RECONNECT_BACKOFF_MS,
  SessionLifecycleRoomBridge,
  disconnectAction,
  idleExpired,
  idlePhaseFor,
  isRecoverableConnectionError,
  lifecyclePhaseFrom,
  needsFreshGrant,
  phaseForReason,
  resolveIdleTimeoutMs,
  resolveReconnectPolicy,
  resolveWarnBeforeMs,
  retryStep,
  shouldReplayPendingTurn,
  useSessionLifecycle,
  type ReconnectPolicy,
  type RecoveryState,
  type RetryStep,
  type RealtimeSessionRoomSinks,
  type SessionEndReason,
  type SessionLifecycleApi,
  type SessionLifecyclePhase,
  type SessionLifecyclePhaseKind,
  type SessionLifecycleRoomBridgeProps,
  type UseSessionLifecycleInput,
} from "./session-lifecycle";
export {
  DEFAULT_APPROACHING_END_LEAD_SECONDS,
  DEFAULT_CREDITS_LOW_LEAD_SECONDS,
  DEFAULT_GRACE_CEILING_SECONDS,
  DEFAULT_GRACE_WINDOW_LEAD_SECONDS,
  useRealtimeSession,
  type ApproachingEndEvent,
  type BehaviorSnapshot,
  type ClipResult,
  type ClosingTurnResult,
  type CreditsLowEvent,
  type EndedEvent,
  type ExtendResult,
  type GraceWindowClosedEvent,
  type GraceWindowOpenEvent,
  type IdleWarningEvent,
  type RealtimeSessionApi,
  type RealtimeSessionMedia,
  type ReconnectingEvent,
  type TurnTimeoutEvent,
  type UseRealtimeSessionInput,
} from "./use-realtime-session";
// Tab-global mic single-flight — the CROSS-call ghost-mic guard (a rapid redial
// must not acquire getUserMedia before the prior room released it). `useMicLease`
// is the React binding adopters fold into their mic-intent signal; the pure
// acquire/release primitives are exported for testing + non-React coordination.
// `useReleaseMicLeaseOnTrackEnded` (from ./livekit) is the in-room companion that
// releases on the mic track's real `ended` event.
export {
  MIC_LEASE_ENDED_TIMEOUT_MS,
  acquireMicLease,
  confirmMicTrackEnded,
  currentMicLeaseHolder,
  pendingMicLeaseRelease,
  releaseMicLease,
  releaseMicLeaseWhenEnded,
  useMicLease,
  type MicLease,
} from "./mic-single-flight";
// Re-export the director ack frame type so consumers can type their onAck handler without
// reaching into the contracts package (the hook's onAck signature uses it).
export {
  approachingEndFrom,
  creditsLowFrom,
  endsAtFrom,
  mapTurnState,
  nextGraceWindow,
  resolveEndReason,
  sessionRemainingMsFrom,
  type ApproachingEndReason,
  type EndReason,
  type GraceWindowState,
  type SessionClocks,
  type TurnState,
} from "./grace-window";
// Adaptive video-quality governor — the PURE anti-flap core (docs/ADAPTIVE_VIDEO_
// QUALITY.md). The app never touches this directly; it uses the hook that wraps it.
export {
  DEFAULT_GOVERNOR_CONFIG,
  capToVideoQuality,
  initGovernor,
  step as stepQualityGovernor,
  type Governor,
  type GovernorAction,
  type GovernorConfig,
  type GovernorSignal,
  type GovernorState,
  type QualityCap,
} from "./quality-governor";
export {
  useAvatarQualityGovernor,
  type FreezeReadingFn,
  type UseAvatarQualityGovernorInput,
} from "./use-quality-governor";
// Multi-clip choreography protocol pieces apps need to build clip libraries + narrow states.
export {
  knownBehaviorStates,
  sessionBehaviorSchema,
  sessionClipSchema,
  type KnownBehaviorState,
  type SessionBehavior,
  type SessionClip,
} from "realtime-avatar-contracts";
