import { z } from "zod";

/** The JSON contract shared by the SDK collector and first-party platform ingestion. */
export const networkEvidenceSchemaVersion = 1 as const;
export const MAX_NETWORK_EVIDENCE_SAMPLES = 480;
export const MAX_NETWORK_EVIDENCE_BATCH = 20;
export const NETWORK_EVIDENCE_DURATION_MS = 30 * 60_000;

const boundedIdSchema = z.string().min(1).max(160);
const safeCountSchema = z.number().int().safe().min(0).max(10_000_000_000);
const millisecondsSchema = z.number().int().safe().min(0).max(86_400_000);
const bitrateSchema = z.number().int().safe().min(0).max(100_000_000);

export const networkEvidenceSurfaceSchema = z.enum(["web", "ios", "android", "unknown"]);
export const networkEvidenceModeSchema = z.enum(["avatar", "voice"]);
export const networkEvidenceTriggerSchema = z.enum([
  "interval",
  "connected",
  "quality",
  "stream_state",
  "reconnecting",
  "reconnected",
  "disconnected",
  "track_subscribed",
  "first_video_frame",
]);
export const networkCandidateTypeSchema = z.enum(["host", "srflx", "prflx", "relay"]);
export const networkCandidateProtocolSchema = z.enum(["udp", "tcp"]);
export const networkTypeSchema = z.enum(["wifi", "cellular", "ethernet"]);
export const networkCodecSchema = z.enum(["h264", "vp8", "vp9", "av1", "opus"]);
export const networkIceStateSchema = z.enum([
  "new",
  "checking",
  "connected",
  "completed",
  "disconnected",
  "failed",
  "closed",
]);
export const networkDtlsStateSchema = z.enum(["new", "connecting", "connected", "closed", "failed"]);
export const networkQualitySchema = z.enum(["excellent", "good", "poor", "lost", "unknown"]);
export const networkConnectionStateSchema = z.enum([
  "disconnected",
  "connecting",
  "connected",
  "reconnecting",
  "signalReconnecting",
]);
export const networkStreamStateSchema = z.enum(["active", "paused", "unknown"]);

export const networkEvidenceContextSchema = z.strictObject({
  /** UUID generated by the app or its server for one evidence segment. */
  evidenceId: z.uuid(),
  callId: boundedIdSchema.optional(),
  attemptId: boundedIdSchema.optional(),
  /** Required for uploadable evidence; pre-mint failures use the app's existing diagnostic lane. */
  sessionId: z.string().regex(/^rts_[a-f0-9]{32}$/),
  surface: networkEvidenceSurfaceSchema,
  mode: networkEvidenceModeSchema,
  clientBuild: boundedIdSchema.optional(),
});

export const networkLiveKitIdentitySchema = z.strictObject({
  roomSid: boundedIdSchema.optional(),
  localParticipantSid: boundedIdSchema.optional(),
  avatarParticipantSid: boundedIdSchema.optional(),
  audioTrackSid: boundedIdSchema.optional(),
  videoTrackSid: boundedIdSchema.optional(),
  region: boundedIdSchema.optional(),
});

export const networkTransportEvidenceSchema = z.strictObject({
  ice: networkIceStateSchema.optional(),
  dtls: networkDtlsStateSchema.optional(),
  /** Candidate type and protocol only, for example `srflx/udp -> relay`. */
  route: z.templateLiteral([
    networkCandidateTypeSchema, "/", networkCandidateProtocolSchema, " -> ", networkCandidateTypeSchema,
  ]).optional(),
  network: networkTypeSchema.optional(),
  rttMs: millisecondsSchema.optional(),
  availableOutgoingBitrate: bitrateSchema.optional(),
  availableIncomingBitrate: bitrateSchema.optional(),
  selectedCandidatePairChanges: safeCountSchema.optional(),
});

export const networkInboundRtpEvidenceSchema = z.strictObject({
  codec: networkCodecSchema.optional(),
  bytesReceived: safeCountSchema.optional(),
  packetsReceived: safeCountSchema.optional(),
  packetsLost: safeCountSchema.optional(),
  jitterMs: millisecondsSchema.optional(),
  jitterBufferDelayMs: millisecondsSchema.optional(),
  jitterBufferEmittedCount: safeCountSchema.optional(),
  framesReceived: safeCountSchema.optional(),
  framesDecoded: safeCountSchema.optional(),
  framesDropped: safeCountSchema.optional(),
  framesPerSecond: z.number().finite().min(0).max(240).optional(),
  frameWidth: safeCountSchema.max(10_000).optional(),
  frameHeight: safeCountSchema.max(10_000).optional(),
  freezeCount: safeCountSchema.optional(),
  totalFreezesDurationMs: millisecondsSchema.optional(),
  keyFramesDecoded: safeCountSchema.optional(),
  concealedSamples: safeCountSchema.optional(),
  totalSamplesReceived: safeCountSchema.optional(),
});

export const networkRtcStatsEvidenceSchema = z.strictObject({
  source: z.enum(["peer_connection", "receiver", "none"]),
  connection: networkTransportEvidenceSchema.optional(),
  video: networkInboundRtpEvidenceSchema.optional(),
  audio: networkInboundRtpEvidenceSchema.optional(),
});

export const networkPresentationEvidenceSchema = z.strictObject({
  /** Web only: proven by rVFC/currentTime. Native must leave these absent until it has equivalent proof. */
  liveFrameSeen: z.boolean().optional(),
  liveFrameFlowing: z.boolean().optional(),
  frameWidth: safeCountSchema.optional(),
  frameHeight: safeCountSchema.optional(),
});

export const networkEvidenceManifestSchema = z.strictObject({
  schemaVersion: z.literal(networkEvidenceSchemaVersion),
  correlation: networkEvidenceContextSchema,
  livekit: networkLiveKitIdentitySchema,
  createdAtUnixMs: z.number().int().safe().min(0),
});

export const networkEvidenceSampleSchema = z.strictObject({
  schemaVersion: z.literal(networkEvidenceSchemaVersion),
  evidenceId: z.uuid(),
  sampleSeq: z.number().int().min(1).max(MAX_NETWORK_EVIDENCE_SAMPLES),
  elapsedMs: millisecondsSchema,
  capturedAtUnixMs: z.number().int().safe().min(0),
  trigger: networkEvidenceTriggerSchema,
  turnId: boundedIdSchema.optional(),
  statsStatus: z.enum(["available", "unavailable"]),
  livekit: z.strictObject({
    connectionState: networkConnectionStateSchema,
    quality: networkQualitySchema,
    videoStreamState: networkStreamStateSchema,
    audioStreamState: networkStreamStateSchema,
    disconnectReason: z.number().int().min(0).max(30).optional(),
  }),
  identity: networkLiveKitIdentitySchema,
  stats: networkRtcStatsEvidenceSchema,
  presentation: networkPresentationEvidenceSchema.optional(),
});

export const networkEvidenceUploadSchema = z.strictObject({
  manifest: networkEvidenceManifestSchema,
  samples: z.array(networkEvidenceSampleSchema).min(1).max(MAX_NETWORK_EVIDENCE_BATCH),
}).superRefine(({ manifest, samples }, ctx) => {
  const seen = new Set<number>();
  for (const [index, sample] of samples.entries()) {
    if (sample.evidenceId !== manifest.correlation.evidenceId || seen.has(sample.sampleSeq)) {
      ctx.addIssue({ code: "custom", path: ["samples", index], message: "sample does not belong to this evidence sequence" });
    }
    seen.add(sample.sampleSeq);
  }
});

export const networkEvidenceAcceptedSchema = z.strictObject({
  accepted: z.number().int().safe().min(0).max(MAX_NETWORK_EVIDENCE_SAMPLES),
});

export const networkEvidenceAnalyticsSchema = z.strictObject({
  quality: networkQualitySchema,
  routeClass: z.enum(["direct", "relay", "unknown"]),
  networkClass: z.enum([...networkTypeSchema.options, "unknown"]),
  rttBucket: z.enum(["lt_100", "100_250", "250_500", "gte_500", "unknown"]),
  videoPaused: z.boolean(),
  videoFrameFlowing: z.boolean().nullable(),
});

export type NetworkEvidenceSurface = z.infer<typeof networkEvidenceSurfaceSchema>;
export type NetworkEvidenceMode = z.infer<typeof networkEvidenceModeSchema>;
export type NetworkEvidenceTrigger = z.infer<typeof networkEvidenceTriggerSchema>;
export type NetworkEvidenceContext = z.infer<typeof networkEvidenceContextSchema>;
export type LiveKitEvidenceIdentity = z.infer<typeof networkLiveKitIdentitySchema>;
export type TransportEvidence = z.infer<typeof networkTransportEvidenceSchema>;
export type InboundRtpEvidence = z.infer<typeof networkInboundRtpEvidenceSchema>;
export type RtcStatsEvidence = z.infer<typeof networkRtcStatsEvidenceSchema>;
export type PresentationEvidence = z.infer<typeof networkPresentationEvidenceSchema>;
export type AvatarNetworkEvidenceManifest = z.infer<typeof networkEvidenceManifestSchema>;
export type AvatarNetworkEvidenceSample = z.infer<typeof networkEvidenceSampleSchema>;
export type AvatarNetworkEvidenceUpload = z.infer<typeof networkEvidenceUploadSchema>;
export type AvatarNetworkEvidenceAccepted = z.infer<typeof networkEvidenceAcceptedSchema>;
export type NetworkEvidenceAnalytics = z.infer<typeof networkEvidenceAnalyticsSchema>;

export type NetworkEvidenceSampleInput = Omit<
  AvatarNetworkEvidenceSample,
  "schemaVersion" | "evidenceId" | "sampleSeq" | "capturedAtUnixMs" | "elapsedMs"
> & {
  elapsedMs?: number;
  capturedAtUnixMs?: number;
};
